//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accomodation
    {
        public System.Guid AccomodationId { get; set; }
        public System.Guid AppUserId { get; set; }
        public Nullable<System.Guid> AssociatedTravelId { get; set; }
        public string AccomodationName { get; set; }
        public string Address { get; set; }
        public System.Guid ContactId { get; set; }
        public string LatLong { get; set; }
        public Nullable<double> DistanceFromAirport { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.Guid> AccomodationProviderId { get; set; }
    
        public virtual AccomodationProvider AccomodationProvider { get; set; }
        public virtual AppUser AppUser { get; set; }
        public virtual Travel Travel { get; set; }
    }
}
