//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppTimeZone
    {
        public AppTimeZone()
        {
            this.Travels = new HashSet<Travel>();
            this.Travels1 = new HashSet<Travel>();
        }
    
        public int TimeZoneId { get; set; }
        public string TimeZoneName { get; set; }
        public double TimeZoneDifference { get; set; }
        public string TimeZoneCode { get; set; }
    
        public virtual ICollection<Travel> Travels { get; set; }
        public virtual ICollection<Travel> Travels1 { get; set; }
    }
}
