//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public AppUser()
        {
            this.Accomodations = new HashSet<Accomodation>();
            this.AppUserLoyalties = new HashSet<AppUserLoyalty>();
            this.Contacts = new HashSet<Contact>();
            this.FamilyProfiles = new HashSet<FamilyProfile>();
            this.Travels = new HashSet<Travel>();
        }
    
        public System.Guid AppUserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Token { get; set; }
    
        public virtual ICollection<Accomodation> Accomodations { get; set; }
        public virtual ICollection<AppUserLoyalty> AppUserLoyalties { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<FamilyProfile> FamilyProfiles { get; set; }
        public virtual ICollection<Travel> Travels { get; set; }
    }
}
