//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociationType
    {
        public AssociationType()
        {
            this.Loyalties = new HashSet<Loyalty>();
        }
    
        public System.Guid AssociationTypeId { get; set; }
        public string AssociationTypeName { get; set; }
    
        public virtual ICollection<Loyalty> Loyalties { get; set; }
    }
}
