//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public System.Guid ContactId { get; set; }
        public System.Guid AppUserId { get; set; }
        public System.Guid ContactTypeId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string Fax { get; set; }
        public string EmailAddress { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public string LatLong { get; set; }
        public bool IsEmergencyContact { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual ContactType ContactType { get; set; }
    }
}
