//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactType
    {
        public ContactType()
        {
            this.Contacts = new HashSet<Contact>();
        }
    
        public System.Guid ContactTypeId { get; set; }
        public string ContactTypeName { get; set; }
        public Nullable<System.Guid> ReferenceId { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
