//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.CountryVisas = new HashSet<CountryVisa>();
            this.States = new HashSet<State>();
            this.VisaApplicables = new HashSet<VisaApplicable>();
        }
    
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public string Currency { get; set; }
    
        public virtual ICollection<CountryVisa> CountryVisas { get; set; }
        public virtual ICollection<State> States { get; set; }
        public virtual ICollection<VisaApplicable> VisaApplicables { get; set; }
    }
}
