//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryVisa
    {
        public CountryVisa()
        {
            this.PassportVisas = new HashSet<PassportVisa>();
            this.VisaApplicables = new HashSet<VisaApplicable>();
        }
    
        public System.Guid CountryVisaId { get; set; }
        public int CountryId { get; set; }
        public byte VisaType { get; set; }
        public string VisaName { get; set; }
        public string VisaDescription { get; set; }
        public double Cost { get; set; }
        public string CostDescription { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual VisaType VisaType1 { get; set; }
        public virtual ICollection<PassportVisa> PassportVisas { get; set; }
        public virtual ICollection<VisaApplicable> VisaApplicables { get; set; }
    }
}
