//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConciergeEntities : DbContext
    {
        public ConciergeEntities()
            : base("name=ConciergeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accomodation> Accomodations { get; set; }
        public DbSet<AccomodationProvider> AccomodationProviders { get; set; }
        public DbSet<AppUser> AppUsers { get; set; }
        public DbSet<AppUserLoyalty> AppUserLoyalties { get; set; }
        public DbSet<AssociationType> AssociationTypes { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<ContactType> ContactTypes { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<CountryVisa> CountryVisas { get; set; }
        public DbSet<FamilyProfile> FamilyProfiles { get; set; }
        public DbSet<Loyalty> Loyalties { get; set; }
        public DbSet<Passport> Passports { get; set; }
        public DbSet<PassportType> PassportTypes { get; set; }
        public DbSet<PassportVisa> PassportVisas { get; set; }
        public DbSet<RelationType> RelationTypes { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<AppTimeZone> AppTimeZones { get; set; }
        public DbSet<Travel> Travels { get; set; }
        public DbSet<TravelMode> TravelModes { get; set; }
        public DbSet<TravelOperator> TravelOperators { get; set; }
        public DbSet<VisaApplicable> VisaApplicables { get; set; }
        public DbSet<VisaType> VisaTypes { get; set; }
    }
}
