//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyProfile
    {
        public FamilyProfile()
        {
            this.Passports = new HashSet<Passport>();
        }
    
        public System.Guid FamilyId { get; set; }
        public System.Guid PassportTypeId { get; set; }
        public System.Guid AppUserId { get; set; }
        public byte RelationTypeId { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int Nationality { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual RelationType RelationType { get; set; }
        public virtual ICollection<Passport> Passports { get; set; }
    }
}
