//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loyalty
    {
        public Loyalty()
        {
            this.AppUserLoyalties = new HashSet<AppUserLoyalty>();
        }
    
        public System.Guid LoyaltyId { get; set; }
        public Nullable<System.Guid> AssociationTypeId { get; set; }
        public Nullable<System.Guid> AssociationReferenceId { get; set; }
        public string LoyaltyName { get; set; }
        public string LoyaltyDescription { get; set; }
    
        public virtual ICollection<AppUserLoyalty> AppUserLoyalties { get; set; }
        public virtual AssociationType AssociationType { get; set; }
    }
}
