//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public Passport()
        {
            this.PassportVisas = new HashSet<PassportVisa>();
        }
    
        public System.Guid PassportId { get; set; }
        public System.Guid FamilyId { get; set; }
        public System.Guid PassportTypeId { get; set; }
        public string Passpot { get; set; }
        public string PassportNumber { get; set; }
        public string PassportIssuedPlace { get; set; }
        public System.DateTime PassportIssueDate { get; set; }
        public System.DateTime PassportExpiryDate { get; set; }
        public int NationalityId { get; set; }
    
        public virtual FamilyProfile FamilyProfile { get; set; }
        public virtual PassportType PassportType { get; set; }
        public virtual ICollection<PassportVisa> PassportVisas { get; set; }
    }
}
