//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassportVisa
    {
        public System.Guid PassportVisaId { get; set; }
        public System.Guid PassportId { get; set; }
        public System.Guid CountryVisaId { get; set; }
        public System.DateTime VisaIssueDate { get; set; }
        public System.DateTime VisaExpiryDate { get; set; }
        public string VisaIssuePlace { get; set; }
    
        public virtual CountryVisa CountryVisa { get; set; }
        public virtual Passport Passport { get; set; }
    }
}
