//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationType
    {
        public RelationType()
        {
            this.FamilyProfiles = new HashSet<FamilyProfile>();
        }
    
        public byte RelationTypeId { get; set; }
        public string RelationTypeName { get; set; }
    
        public virtual ICollection<FamilyProfile> FamilyProfiles { get; set; }
    }
}
