//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelOperator
    {
        public TravelOperator()
        {
            this.Travels = new HashSet<Travel>();
        }
    
        public System.Guid TravelOperatorId { get; set; }
        public byte TravelModeId { get; set; }
        public string OperatorName { get; set; }
        public Nullable<int> OperatorNationality { get; set; }
    
        public virtual ICollection<Travel> Travels { get; set; }
        public virtual TravelMode TravelMode { get; set; }
    }
}
