//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concierge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelMode
    {
        public TravelMode()
        {
            this.Travels = new HashSet<Travel>();
            this.TravelOperators = new HashSet<TravelOperator>();
        }
    
        public byte TravelModeId { get; set; }
        public string TravelModeName { get; set; }
    
        public virtual ICollection<Travel> Travels { get; set; }
        public virtual ICollection<TravelOperator> TravelOperators { get; set; }
    }
}
